import { defineField, defineType } from "sanity";

//@ts-ignore
export const product = defineType({
    name:'product',
    title:'Products',
    type:'document',
    fields:[
        //@ts-ignore
        defineField({
            name:'name',
            title:'Name',
            type:'string'
        }),
        {
            name:'slug',
            title:'Slug',
            type:'slug',
            options:{source:'name'}
        },
        {
            name:'images',
            title:'Images',
            type:'array',
            of:[{type:'image'}]
        },
        {
            name:'description',
            title:'Description',
            type:'array',
            of:[{type:'block'}]
        },
        {
            name:'price',
            title:'Price',
            type:'number'
        }
    ]
})